set(_CATKIN_CURRENT_PACKAGE "zed_subscriber")
set(zed_subscriber_VERSION "0.0.0")
set(zed_subscriber_MAINTAINER "jfrancis <jfrancis@todo.todo>")
set(zed_subscriber_PACKAGE_FORMAT "2")
set(zed_subscriber_BUILD_DEPENDS "roscpp" "sensor_msgs")
set(zed_subscriber_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msgs")
set(zed_subscriber_BUILDTOOL_DEPENDS "catkin")
set(zed_subscriber_BUILDTOOL_EXPORT_DEPENDS )
set(zed_subscriber_EXEC_DEPENDS "roscpp" "sensor_msgs")
set(zed_subscriber_RUN_DEPENDS "roscpp" "sensor_msgs")
set(zed_subscriber_TEST_DEPENDS )
set(zed_subscriber_DOC_DEPENDS )
set(zed_subscriber_URL_WEBSITE "")
set(zed_subscriber_URL_BUGTRACKER "")
set(zed_subscriber_URL_REPOSITORY "")
set(zed_subscriber_DEPRECATED "")